apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: deployment_with_argocd/manifest
    repoURL: 'https://github.com/yongpete/devops_handson'
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true